@startuml
skinparam classAttributeIconSize 0
class Constants{
+ {static} STATUS_NORMAL : int
+ {static} STATUS_HALT : int
+ {static} COMMENT_SPACE_OFFSET : int
+ {static} COBOLCHECK_PACKAGE_PATH : String
+ {static} COBOLCHECK_COPYBOOK_DIRECTORY : String
+ {static} COMMAND_lINE_OPTIONS : String
+ {static} EMPTY_STRING : String
+ {static} NEWLINE : String
+ {static} FILE_SEPARATOR : String
+ {static} CURRENT_DIRECTORY : String
+ {static} PERIOD : String
+ {static} COMMENT_INDICATOR : String
+ {static} COLON : String
+ {static} SPACE : String
+ {static} COMMA : String
+ {static} QUOTE : String
+ {static} APOSTROPHE : String
+ {static} PSEUDO_TEXT_DELIMITER_EQUALS : String
+ {static} PSEUDO_TEXT_DELIMITER_COLON : String
+ {static} TRUE : String
+ {static} FALSE : String
+ {static} TESTSUITE_KEYWORD : String
+ {static} TESTCASE_KEYWORD : String
+ {static} EXPECT_KEYWORD : String
+ {static} FIELDNAME_KEYWORD : String
+ {static} TO_BE_KEYWORD : String
+ {static} TO_EQUAL_KEYWORD : String
+ {static} NOT_KEYWORD : String
+ {static} ALPHANUMERIC_LITERAL_KEYWORD : String
+ {static} PARENTHESIS_ENCLOSED_KEYWORD : String
+ {static} NUMERIC_LITERAL_KEYWORD : String
+ {static} COBOL_TOKEN : String
+ {static} BOOLEAN_VALUE : String
+ {static} REPLACING_KEYWORD : String
+ {static} BY_KEYWORD : String
+ {static} EQUAL_SIGN_KEYWORD : String
+ {static} NOT_EQUAL_SIGN_KEYWORD : String
+ {static} GREATER_THAN_SIGN_KEYWORD : String
+ {static} LESS_THAN_SIGN_KEYWORD : String
+ {static} GREATER_THAN_EQUAL_TO_SIGN_KEYWORD : String
+ {static} LESS_THAN_EQUAL_TO_SIGN_KEYWORD : String
+ {static} MOCK_KEYWORD : String
+ {static} MOCK_TYPE : String
+ {static} QUALIFIED_FIELD_NAME : String
+ {static} ENDMOCK_KEYWORD : String
+ {static} VERIFY_KEYWORD : String
+ {static} NEVER_HAPPENED_KEYWORD : String
+ {static} HAPPENED_KEYWORD : String
+ {static} ONCE_KEYWORD : String
+ {static} AT_LEAST_KEYWORD : String
+ {static} NO_MORE_THAN_KEYWORD : String
+ {static} TIME_KEYWORD : String
+ {static} TIMES_KEYWORD : String
+ {static} BEFORE_EACH_TOKEN : String
+ {static} END_BEFORE_TOKEN : String
+ {static} AFTER_EACH_TOKEN : String
+ {static} END_AFTER_TOKEN : String
+ {static} NUMERIC_KEYWORD : String
+ {static} IN_KEYWORD : String
+ {static} OF_KEYWORD : String
+ {static} BEFORE_EACH_TOKEN_HYPHEN : String
+ {static} AFTER_EACH_TOKEN_HYPHEN : String
+ {static} PARA_TOKEN : String
+ {static} IGNORED_TOKENS : List<String>
+ {static} CONCATENATED_TEST_SUITES_CONFIG_KEY : String
+ {static} DEFAULT_CONCATENATED_TEST_SUITES_PATH : String
+ {static} TEST_PROGRAM_NAME_CONFIG_KEY : String
+ {static} DEFAULT_TEST_PROGRAM_NAME : String
+ {static} PROCESS_CONFIG_KEY : String
+ {static} COBOLCHECK_PREFIX_CONFIG_KEY : String
+ {static} DEFAULT_COBOLCHECK_PREFIX : String
+ {static} TEST_CODE_PREFIX_PLACEHOLDER : String
+ {static} TESTS_OPTION : String
+ {static} PROGRAMS_OPTION : String
+ {static} IDENTIFICATION_DIVISION : String
+ {static} ENVIRONMENT_DIVISION : String
+ {static} CONFIGURATION_SECTION : String
+ {static} SPECIAL_NAMES_PARAGRAPH : String
+ {static} INPUT_OUTPUT_SECTION : String
+ {static} FILE_CONTROL : String
+ {static} DATA_DIVISION : String
+ {static} PROCEDURE_DIVISION : String
+ {static} FILE_SECTION : String
+ {static} LOCAL_STORAGE_SECTION : String
+ {static} LINKAGE_SECTION : String
+ {static} WORKING_STORAGE_SECTION : String
+ {static} SELECT_TOKEN : String
+ {static} FILE_STATUS_TOKEN : String
+ {static} IS_TOKEN : String
+ {static} DECIMAL_POINT_KEYWORD : String
+ {static} COMMA_KEYWORD : String
+ {static} FD_TOKEN : String
+ {static} LEVEL_01_TOKEN : String
+ {static} COPY_TOKEN : String
+ {static} SECTION_TOKEN : String
+ {static} CALL_TOKEN : String
+ {static} USING_TOKEN : String
+ {static} BY_REFERENCE_TOKEN : String
+ {static} BY_CONTENT_TOKEN : String
+ {static} BY_VALUE_TOKEN : String
+ {static} DECLARATIVES_TOKEN : String
+ {static} EXIT_TOKEN : String
+ {static} END_SECTION_TOKEN : String
+ {static} END_PARAGRAPH_TOKEN : String
+ {static} END_CALL_TOKEN : String
+ {static} ZERO_TOKEN : String
+ {static} REPLACE_TOKEN : String
+ {static} CBL_TOKEN : String
+ {static} EXEC_SQL_TOKEN : String
+ {static} EXEC_CICS_TOKEN : String
+ {static} END_EXEC_TOKEN : String
+ {static} CONTINUE_TOKEN : String
+ {static} INCLUDE : String
+ {static} BINARY : String
+ {static} COMP_2_VALUE : String
+ {static} COMP_3_VALUE : String
+ {static} COMP_4_VALUE : String
+ {static} COMP_5_VALUE : String
+ {static} COMP_VALUE : String
+ {static} PIC_VALUE : String
+ {static} PICTURE_VALUE : String
+ {static} NUMERIC_PICTURE_CLAUSE_PATTERN : String
+ {static} PARAGRAPH_TOKEN : String
- Constants()
}
@enduml