@startuml
skinparam classAttributeIconSize 0
class RunInfo{
- {static} currentProgramName : String
- {static} currentProgramPath : String
- {static} testSuiteNameToPathMap : Map<String,String>
- {static} configFilePath : String
- {static} generatedCobolSourcePath : String
- {static} compiledProgramPath : String
+ {static} setCurrentProgramName(programName : String) : void
+ {static} getCurrentProgramName() : String
+ {static} getCurrentProgramPath() : String
+ {static} setCurrentProgramPath(currentProgramPath : String) : void
+ {static} getTestSuitePath(testSuiteName : String) : String
+ {static} addTestSuiteNameToPathMapKeyValuePair(testSuiteName : String, path : String) : void
+ {static} getConfigFilePath() : String
+ {static} setConfigFilePath(configFilePath : String) : void
+ {static} getGeneratedCobolSourcePath() : String
+ {static} setGeneratedCobolSourcePath(generatedCobolSourcePath : String) : void
+ {static} getCompiledProgramPath() : String
}
@enduml