@startuml
skinparam classAttributeIconSize 0
class StringHelper{
+ {static} isBlank(subject : String) : boolean
+ {static} notBlank(subject : String) : boolean
+ {static} defaultIfBlank(subject : String, defaultValue : String) : String
+ {static} isEmptyArray(subject : String[]) : boolean
+ {static} fixedLength(sourceLine : String) : String
+ {static} adjustPathString(pathString : String) : String
+ {static} changeFileExtension(path : String, extension : String) : String
+ {static} removeTrailingSpaces(line : String) : String
+ {static} occursFirst(text : String, expectedFirst : char, expectedSecond : char) : boolean
+ {static} swapChars(text : String, c1 : char, c2 : char) : String
+ {static} commentOutLine(line : String) : String
+ {static} stubLine(line : String, stubTag : String) : String
+ {static} getNumberOfLeadingSpaces(line : String) : int
+ {static} ExcludeBetweenTags(value : String, startTag : char, endTag : char) : String
+ {static} isStringContinuationLine(line : String) : boolean
+ {static} moveToAreaB(line : String) : String
+ {static} moveToAreaB(lines : List<String>) : List<String>
+ quote(value : String) : String
+ {static} removeLastIndex(value : String) : String
+ {static} equalsAny(value : String, collection : Collection<String>) : boolean
+ {static} containsAny(value : String, collection : Collection<String>) : boolean
+ {static} startsWithAny(value : String, collection : Collection<String>) : boolean
}
class TestSuiteParserController{
- testSuiteParser : TestSuiteParser
testSuiteConcatenator : TestSuiteConcatenator
- mockRepository : MockRepository
- beforeAfterRepo : BeforeAfterRepo
- mockGenerator : MockGenerator
- testSuiteReader : BufferedReader
- whenOtherGenerator : WhenOtherGenerator
- testSuiteErrorLog : TestSuiteErrorLog
- parsedTestSuiteLines : List<String>
- {static} workingStorageCopybookFilename : String
- {static} procedureDivisionResultCopybookFilename : String
- {static} procedureDivisionParagraphCopybookFilename : String
- {static} copyBookTokensWithPeriodAsDecimalPoint : String[]
- workingStorageHeader : String
- testCodePrefix : String
- workingStorageTestCodeHasBeenInserted : boolean
+ TestSuiteParserController(testFileNames : String)
+ TestSuiteParserController(reader : BufferedReader)
+ hasWorkingStorageTestCodeBeenInserted() : boolean
+ getWorkingStorageHeader() : String
+ concatenateTestSuites(programTestSuiteSubdirectory : String) : void
+ parseTestSuites(numericFields : NumericFields) : void
+ getWorkingStorageTestCode(fileSectionStatements : List<String>) : List<String>
+ getWorkingStorageMockCode() : List<String>
+ generateMockCountingFields() : List<String>
+ getProcedureDivisionTestCode() : List<String>
+ generateMockCountInitializer() : List<String>
+ generateMockSections(withComments : boolean) : List<String>
+ generateBeforeParagraph() : List<String>
+ generateAfterParagraph() : List<String>
+ generateBeforeAfterBranchParagraphs(withComments : boolean) : List<String>
+ generateCobolLinesForUnmockedCalls() : List<String>
+ mockExistsFor(identifier : String, type : String, arguments : List<String>) : boolean
+ generateMockPerformCalls(identifier : String, type : String, arguments : List<String>) : List<String>
+ getEndEvaluateLine() : List<String>
+ logUnusedMocks() : void
+ getBoilerplateCodeFromCopybooks(copybookFilename : String) : List<String>
+ closeTestSuiteReader() : void
+ prepareNextParse() : void
+ generateWhenOtherSectionOrParagraph(type : String, sectionOrParagraphlines : List<String>, sourceLine : String, identifier : String, withComments : boolean) : List<String>
}
class SectionOrParagraph{
- lines : List<String>
+ SectionOrParagraph()
addLine(line : String) : void
getLines() : List<String>
removeLines() : void
}
class ExpectedConfigSettingNotFoundException{
+ ExpectedConfigSettingNotFoundException(message : String)
}
ExpectedConfigSettingNotFoundException --|> RuntimeException
class Testcase{
- name : String
- assertions : String
- classname : String
- status : String
- time : String
- skipped : Skipped
- error : Error
- failure : Error
- systemOut : String
- systemErr : String
+ getSkipped() : Skipped
+ setSkipped(value : Skipped) : void
+ getError() : Error
+ setError(value : Error) : void
+ getFailure() : Error
+ setFailure(value : Error) : void
+ getSystemOut() : String
+ setSystemOut(value : String) : void
+ getSystemErr() : String
+ setSystemErr(value : String) : void
+ getName() : String
+ setName(value : String) : void
+ getAssertions() : String
+ setAssertions(value : String) : void
+ getClassname() : String
+ setClassname(value : String) : void
+ getStatus() : String
+ setStatus(value : String) : void
+ getTime() : String
+ setTime(value : String) : void
}
class JUnitDto{
- testsuites : Testsuites
+ getTestsuites() : Testsuites
+ setTestsuites(value : Testsuites) : void
+ setTestCounts() : void
+ moveToNextTestSuite() : void
+ moveToNextTestCase() : void
+ getDataTransferObject() : Object
+ setNumberOfAllTests(numberofTests : String) : void
+ setNumberOffAllFailures(numberOfFailures : String) : void
+ setCurrentTestSuiteName(name : String) : void
+ setCurrentTestSuiteTests(numberofTests : String) : void
+ setCurrentTestSuiteFailures(numberOfFailures : String) : void
+ setCurrentTestSuitePackage(testSuitePackage : String) : void
+ setCurrentTestCaseName(name : String) : void
+ setCurrentTestCaseFailure(message : String, type : String) : void
+ setCurrentTestCaseErrorMessage(message : String, type : String) : void
}
JUnitDto --|> DataTransferObject
class CurrentStatus{
exitStatus : int
sourceProgramNames : String[]
testFileNames : String
+ CurrentStatus()
}
class ReplaceStatementLocator{
- replaceSets : LinkedList<ReplaceSet>
- tokenizer : ReplaceTokenizer
# currentStatement : StringBuilder
# statementLineNumber : int
# we_are_parsing_a_replace_statement : boolean
# sourceLinesProcessed : int
# commentLinesFound : int
- currentSourcecodeLine : int
+ ReplaceStatementLocator()
+ ReplaceStatementLocator(cobolFile : File)
+ getReplaceSets() : LinkedList<ReplaceSet>
# accumulateStatement(line : String, sourceLineNumber : int) : void
# updateUntilInReplaceSets(fromSourceLine : int, untilSourceLine : int) : void
# createStatements(statement : String, sourceLineNumber : int) : void
- {static} getNewReplaceSet(sourceLineNumber : int) : ReplaceSet
}
class TableDocumentDto{
+ getDataTransferObject() : Object
- getHtmlHeader() : String
- getHtmlEnd() : String
}
TableDocumentDto --|> TableEmbedDto
class TestResultsInputFileNotFoundException{
+ TestResultsInputFileNotFoundException(message : String)
+ TestResultsInputFileNotFoundException(cause : Throwable)
+ TestResultsInputFileNotFoundException(message : String, cause : Throwable)
}
TestResultsInputFileNotFoundException --|> RuntimeException
class TestSuiteAlreadyExistsException{
+ TestSuiteAlreadyExistsException(message : String)
+ TestSuiteAlreadyExistsException(cause : Throwable)
+ TestSuiteAlreadyExistsException(message : String, cause : Throwable)
}
TestSuiteAlreadyExistsException --|> RuntimeException
class EmptyTestSuiteException{
+ EmptyTestSuiteException(message : String)
}
EmptyTestSuiteException --|> RuntimeException
class Mock{
- identifier : String
- type : String
- lines : List<String>
- arguments : List<String>
- scope : MockScope
- isUsed : boolean
- testSuiteName : String
- testCaseName : String
- testSuiteNumber : int
- testCaseNumber : int
- mockNumber : int
- testSuiteFileName : String
- declarationLineNumberInOriginalFile : int
- declarationIndexNumberInOriginalFile : int
+ Mock(testSuiteName : String, testCaseName : String, testSuiteNumber : int, testCaseNumber : int, mockNumber : int)
+ getGeneratedMockIdentifierRoot() : String
+ getGeneratedMockIdentifier() : String
+ getGeneratedMockCountIdentifier() : String
+ getGeneratedMockCountExpectedIdentifier() : String
+ getGeneratedMockStringIdentifierName() : String
+ getMockDisplayString() : String
+ getMockDescription() : String
+ getCommentText() : List<String>
+ getIdentifier() : String
+ getType() : String
+ getLines() : List<String>
+ getArguments() : List<String>
+ getScope() : MockScope
+ isUsed() : boolean
+ getTestSuiteName() : String
+ getTestCaseName() : String
+ setIdentifier(identifier : String) : void
+ setType(type : String) : void
+ setScope(scope : MockScope) : void
+ markAsUsed() : void
+ addLine(line : String) : void
+ addLines(lines : List<String>) : void
+ addArgument(argument : String) : void
+ getTestSuiteFileName() : String
+ setTestSuiteFileName(testSuiteFileName : String) : void
+ getDeclarationLineNumberInOriginalFile() : int
+ setDeclarationLineNumberInOriginalFile(declarationLineNumberInOriginalFile : int) : void
+ getDeclarationIndexNumberInOriginalFile() : int
+ setDeclarationIndexNumberInOriginalFile(declarationIndexNumberInOriginalFile : int) : void
- getArgumentText() : String
}
class HTMLFormat{
+ HTMLFormat(dataTransferObjectStyle : DataTransferObjectStyle)
+ writeInFormat(path : String) : String
}
HTMLFormat --|> Formatter
class IOExceptionProcessingTestResultFile{
+ IOExceptionProcessingTestResultFile(filename : String)
+ IOExceptionProcessingTestResultFile(ex : Throwable)
+ IOExceptionProcessingTestResultFile(filename : String, ex : Throwable)
}
IOExceptionProcessingTestResultFile --|> RuntimeException
class KeywordExtractor{
- multiWordTokens : Map<String,List<String>>
- buffer : StringBuilder
- PERIOD : char
- COMMA : char
- DOUBLE_QUOTE : char
- SINGLE_QUOTE : char
- SPACE : char
- nextExpectedTokens : List<String>
- openQuote : boolean
- openParenthesis : boolean
- quoteDelimiter : char
- processingNumericLiteral : boolean
+ KeywordExtractor()
+ extractTokensFrom(sourceLine : String) : List<String>
- handleEndOfWord(sourceLine : String, tokens : List<String>, tokenOffset : int) : int
+ tokenListEndsDuringMultiToken(tokens : List<String>) : boolean
- isQuote(character : char) : boolean
- startNumericLiteral(buffer : StringBuilder, currentCharacter : char) : boolean
- isDecimalPoint(buffer : StringBuilder, currentCharacter : char, sourceLine : String, tokenOffset : int) : boolean
- getPreviousCharacterFromBuffer(buffer : StringBuilder) : char
- addTokenAndClearBuffer(buffer : StringBuilder, tokens : List<String>) : StringBuilder
}
KeywordExtractor ..|> TokenExtractor
class TestSuiteCouldNotBeReadException{
+ TestSuiteCouldNotBeReadException(cause : Throwable)
}
TestSuiteCouldNotBeReadException --|> RuntimeException
class Main{
+ {static} main(args : String[]) : void
}
class Version{
+ {static} current() : String
}
class EIBResponseTable{
- {static} EIBResponsesTable : Map<String,EIBResponseCodes>
+ {static} lookup(conditionName : String) : EIBResponseCodes
}
class CommandLineArgumentException{
+ CommandLineArgumentException(message : String)
}
CommandLineArgumentException --|> RuntimeException
class WriterController{
- cobolWriter : CobolWriter
+ WriterController(testSourceWriter : Writer)
+ WriterController(cobolWriter : CobolWriter)
+ startStoringLines() : void
+ stopStoringLines() : void
+ releaseStoredLines() : void
+ writeLine(line : String) : void
+ writeCommentedLine(line : String) : void
+ writeStubbedLine(line : String) : void
+ writeLines(lines : List<String>) : void
+ writeCommentedLines(lines : List<String>) : void
+ writeStubbedLines(lines : List<String>) : void
+ closeWriter(programName : String) : void
}
class Flag{
- state : boolean
- mutuallyExclusiveFlags : List<Flag>
- dependentFlags : List<Flag>
+ Flag()
+ setMutuallyExclusiveFlags(mutuallyExclusiveFlags : List<Flag>) : void
+ setDependentFlags(dependentFlags : List<Flag>) : void
+ isSet() : boolean
+ set() : void
+ unset() : void
}
class ProcessOutputWriter{
testResultsFilePath : String
writeWasSuccesful : boolean
processInput : String
processError : String
xmlFormat : XMLFormat
htmlFormat : HTMLFormat
+ ProcessOutputWriter()
+ getTestResultsFilePath() : String
+ WriteWasSuccesful() : boolean
+ writeProcessOutputToTestResultsFile(proc : Process, format : TestOutputFormat, style : DataTransferObjectStyle, programName : String, outputToConsole : boolean, isLastRun : boolean) : void
- getProcessOut(proc : Process) : void
- writeOutPutToConsole() : void
- writeProcessOutputToFile(path : String) : boolean
- writeProcessOutputWithFormat(formatter : Formatter, programName : String, writeToFile : boolean) : void
- cleanupOldTestResults() : void
}
class LauncherController{
- launcher : Launcher
- processOutputWriter : ProcessOutputWriter
+ LauncherController()
+ runTestProgram(programName : String, isLastRun : boolean) : int
}
class EvaluationGenerator{
- EVALUATE_START : String
- WHEN_FORMAT1 : String
- WHEN_FORMAT2 : String
- PERFORM_FORMAT : String
- WHEN_OTHER_LINE : String
- END_EVALUATE_LINE : String
- ANY_KEYWORD : String
- ALSO_KEYWORD : String
argumentIdentifiers : String[]
evaluationItems : List<EvaluationItem>
+ EvaluationGenerator(argumentIdentifiers : String)
+ containsItems() : boolean
+ addEvaluationItem(line : String, arguments : String) : void
+ addEvaluationItem(lines : String[], arguments : String) : void
+ getEvaluationLines(withWhenOther : boolean, whenOtherLines : Collection<String>, withEndEvaluate : boolean) : List<String>
- getEvaluationHeader() : List<String>
- getEvaluationBody() : List<String>
}
class EvaluationItem{
arguments : String[]
lines : String[]
EvaluationItem(lines : String[], arguments : String)
}
class CobolWriter{
writer : Writer
- currentLineIsComment : boolean
- maxLineLength : int
- storeLines : boolean
- storedLines : List<String>
- stubTag : String
+ CobolWriter(writer : Writer)
writeLine(line : String) : void
+ startStoringLines() : void
+ stopStoringLines() : void
+ releaseStoredLines() : void
writeCommentedLine(line : String) : void
writeStubbedLine(line : String) : void
writeFormattedLine(format : String, args : Object) : void
writeLines(lines : List<String>) : void
writeCommentedLines(lines : List<String>) : void
writeStubbedLines(lines : List<String>) : void
close() : void
- writeMultiLine(line : String, isComment : boolean, isRecursiveCall : boolean) : void
- getStringContinuationSign(line1 : String, line2 : String) : char
}
class CobolVerbs{
- {static} values : List<String>
- {static} allVerbs : List<String>
- CobolVerbs()
+ {static} isCobolVerb(token : String) : boolean
+ {static} isStartOrEndCobolVerb(token : String) : boolean
}
class PossibleInternalLogicErrorException{
+ PossibleInternalLogicErrorException(message : String)
+ PossibleInternalLogicErrorException(cause : Throwable)
+ PossibleInternalLogicErrorException(message : String, cause : Throwable)
}
PossibleInternalLogicErrorException --|> RuntimeException
class UndefinedKeywordException{
+ UndefinedKeywordException(message : String)
}
UndefinedKeywordException --|> RuntimeException
class TestSuiteInputFileNotFoundException{
+ TestSuiteInputFileNotFoundException(message : String)
+ TestSuiteInputFileNotFoundException(cause : Throwable)
+ TestSuiteInputFileNotFoundException(message : String, cause : Throwable)
}
TestSuiteInputFileNotFoundException --|> RuntimeException
class EIBResponseCodes{
- EIBFN : byte
- EIBRCODE : byte
- EIBRCODEOffset : int
- EIBRESP : int
+ EIBResponseCodes(EIBFN : byte, EIBRCODE : byte, EIBRCODEOffset : int, EIBRESP : int)
+ EIBFN() : byte
+ EIBRCODE() : byte
+ EIBRCODEOffset() : int
+ EIBRESP() : int
}
class OptionValue{
+ hasArgument : boolean
+ isSet : boolean
+ argumentValue : String
}
class WhenOtherGenerator{
- performFormat : String
generateWhenOtherCall(whenOther : WhenOther) : String
generateWhenOther(whenOther : WhenOther, withComments : boolean) : List<String>
- generateParagraphsForWhenOther(whenOther : WhenOther, withComments : boolean) : List<String>
}
class EncodingIO{
+ {static} getReaderWithCorrectEncoding(path : String) : Reader
+ {static} getWriterWithCorrectEncoding(path : String) : Writer
+ {static} getWriterWithCorrectEncoding(path : String, append : boolean) : Writer
}
class VerifyMockCount{
- attachedMock : Mock
- expectedCount : String
- atLeast : boolean
- noMoreThan : boolean
- identifier : String
- type : String
- arguments : List<String>
- testSuiteFileName : String
- declarationLineNumberInOriginalFile : int
- declarationIndexNumberInOriginalFile : int
+ VerifyMockCount()
+ getExpectedCount() : String
+ isSetToAtLeast() : boolean
+ isSetToNoMoreThan() : boolean
+ getAttachedMock() : Mock
+ getIdentifier() : String
+ getType() : String
+ setType(type : String) : void
+ setIdentifier(identifier : String) : void
+ setAttachedMock(attachedMock : Mock) : void
+ setExpectedCount(expectedCount : String) : void
+ getTestSuiteFileName() : String
+ setTestSuiteFileName(testSuiteFileName : String) : void
+ getDeclarationLineNumberInOriginalFile() : int
+ setDeclarationLineNumberInOriginalFile(declarationLineNumberInOriginalFile : int) : void
+ getDeclarationIndexNumberInOriginalFile() : int
+ setDeclarationIndexNumberInOriginalFile(declarationIndexNumberInOriginalFile : int) : void
expectExact(expectedCount : String) : void
expectAtLeast(expectedCount : String) : void
expectNoMoreThan(expectedCount : String) : void
+ getArguments() : List<String>
+ addArgument(argument : String) : void
}
class ReplaceToken{
- value : String
- type : ReplaceTokenType
+ ReplaceToken(value : String)
- setType() : void
+ getValue() : String
+ getType() : ReplaceTokenType
}
class ReplaceTokenizer{
- position : int
- tokens : LinkedList<ReplaceToken>
- isComment : boolean
- {static} GROUP_COMMENT_INDICATOR : int
- {static} COMMENT_INDICATOR : String
- {static} replacePattern : Pattern
- {static} isCommentPattern : Pattern
+ tokenize(line : String) : void
+ hasMoreTokens() : boolean
+ nextToken() : ReplaceToken
+ isComment() : boolean
}
class CobolTestRunner{
controller : LauncherController
+ run(programName : String, isLastRun : boolean) : int
}
class StringTokenizerExtractor{
- {static} delimiters : String
- {static} expectedTokens : Map<String,List<String>>
+ StringTokenizerExtractor()
+ extractTokensFrom(sourceLine : String) : List<String>
- swapStringsOutWithMappedTokens(line : String, stringTokensToString : Map<String,String>) : String
- swapMappedTokensOutWithSavedStrings(tokens : List<String>, stringTokensToString : Map<String,String>) : void
}
StringTokenizerExtractor ..|> TokenExtractor
class TestSuiteParser{
- keywordExtractor : KeywordExtractor
- testSuiteWritingStyle : TestSuiteWritingStyle
- testSuiteTokens : List<String>
- testNamesHierarchy : HashMap<String,HashSet<String>>
- currentTestSuiteLine : String
- fileLineNumber : int
- fileLineIndexNumber : int
- currentTestSuiteRealFile : String
- oldTestSuiteRealFile : String
- currentFieldName : String
- testSuiteErrorLog : TestSuiteErrorLog
- beforeAfterRepo : BeforeAfterRepo
mockRepository : MockRepository
- currentMock : Mock
- parsingDataUsing : String
- mockNumber : int
- expectMockIdentifier : boolean
expectUsing : boolean
expectMockArguments : boolean
- ignoreCobolStatementAndFieldNameKeyAction : boolean
- currentVerify : VerifyMockCount
- verifyInProgress : boolean
- testCodePrefix : String
- emptyTestSuite : boolean
- cobolStatementInProgress : boolean
- expectInProgress : boolean
- toBeInProgress : boolean
- boolean88LevelCompare : boolean
- expectTestsuiteName : boolean
- expectTestcaseName : boolean
- fieldNameForExpect : String
- possibleQualifiedName : boolean
- expectQualifiedName : boolean
- expectedValueToCompare : String
- reverseCompare : boolean
- greaterThanComparison : boolean
- lessThanComparison : boolean
- nextAction : KeywordAction
- currentTestSuiteName : String
- testSuiteNumber : int
- currentTestCaseName : String
- testCaseNumber : int
- expectNumericCompare : boolean
- whenOtherNumber : int
- {static} COBOL_PERFORM_INITIALIZE : String
- {static} COBOL_DISPLAY_TESTSUITE : String
- {static} COBOL_DISPLAY_NAME : String
- {static} COBOL_STORE_TESTCASE_NAME_1 : String
- {static} COBOL_STORE_TESTCASE_NAME_2 : String
- {static} COBOL_STORE_TESTSUITE_NAME_1 : String
- {static} COBOL_STORE_TESTSUITE_NAME_2 : String
- {static} COBOL_PERFORM_BEFORE : String
- {static} COBOL_PERFORM_INITIALIZE_MOCK_COUNT : String
- {static} COBOL_INCREMENT_TEST_CASE_COUNT : String
- {static} COBOL_SET_NORMAL_OR_REVERSE_COMPARE : String
- {static} COBOL_SET_COMPARE_NUMERIC : String
- {static} COBOL_SET_COMPARE_88_LEVEL : String
- {static} COBOL_SET_RELATION : String
- {static} COBOL_MOVE_FIELDNAME_TO_ACTUAL : String
- {static} COBOL_MOVE_FIELDNAME_TO_ACTUAL_NUMERIC : String
- {static} COBOL_MOVE_EXPECTED_ALPHANUMERIC_LITERAL_1 : String
- {static} COBOL_MOVE_EXPECTED_ALPHANUMERIC_LITERAL_2 : String
- {static} COBOL_MOVE_EXPECTED_NUMERIC_LITERAL : String
- {static} COBOL_SET_ACTUAL_88_VALUE_1 : String
- {static} COBOL_SET_ACTUAL_88_VALUE_2 : String
- {static} COBOL_SET_ACTUAL_88_VALUE_3 : String
- {static} COBOL_SET_ACTUAL_88_VALUE_4 : String
- {static} COBOL_SET_ACTUAL_88_VALUE_5 : String
- {static} COBOL_SET_ACTUAL_88_VALUE_6 : String
- {static} COBOL_SET_ACTUAL_88_VALUE_7 : String
- {static} COBOL_SET_EXPECTED_88_VALUE_1 : String
- {static} COBOL_SET_EXPECTED_88_VALUE_2 : String
- {static} COBOL_SET_EXPECTED_88_VALUE_3 : String
- {static} COBOL_SET_EXPECTED_88_VALUE_4 : String
- {static} COBOL_SET_EXPECTED_88_VALUE_5 : String
- {static} COBOL_SET_EXPECTED_88_VALUE : String
- {static} COBOL_SET_ALPHANUMERIC_COMPARE : String
- {static} COBOL_CHECK_EXPECTATION : String
- {static} COBOL_PERFORM_AFTER : String
- {static} ELEVEN_LEADING_SPACES : String
- {static} COBOL_SET_ACTUAL_MOCK_ACCESSES : String
- {static} COBOL_SET_EXPECTED_MOCK_ACCESSES : String
- {static} COBOL_SET_MOCK_OPERATION : String
- {static} COBOL_SET_VERIFY_EXACT : String
- {static} COBOL_SET_VERIFY_AT_LEAST : String
- {static} COBOL_SET_VERIFY_NO_MORE_THAN : String
- {static} COBOL_PERFORM_ASSERT_ACCESS : String
- {static} COBOL_MOVE : String
- {static} RELATION_EQ : String
- {static} RELATION_GT : String
- {static} RELATION_LT : String
- {static} NORMAL : String
- {static} REVERSE : String
- cobolStatement : StringBuffer
- numericFields : NumericFields
+ TestSuiteParser(keywordExtractor : KeywordExtractor, mockRepository : MockRepository, beforeAfterRepo : BeforeAfterRepo, testSuiteErrorLog : TestSuiteErrorLog)
+ getParsedTestSuiteLines(testSuiteReader : BufferedReader, numericFieldsList : NumericFields) : List<String>
+ containStopValue(testSuiteToken : String) : boolean
- removeToken(lines : List<String>, token : String) : List<String>
- getNextTokenFromTestSuite(testSuiteReader : BufferedReader) : String
- readNextLineFromTestSuite(testSuiteReader : BufferedReader) : String
- getWritingStyleOfLine(line : String) : TestSuiteWritingStyle
- handleEndOfMockStatement(testSuiteReader : BufferedReader, testSuiteToken : String, skipCurrentToken : boolean, tracker : TokenTracker) : void
+ handleEndOfVerifyStatement(parsedTestSuiteLines : List<String>, tracker : TokenTracker) : void
- getCallArgument(referenceType : String, value : String) : String
+ getTestInitializationLine() : String
+ addTestSuiteNamelines(testSuiteName : String, parsedTestSuiteLines : List<String>) : void
+ addTestCaseNameLines(testCaseName : String, parsedTestSuiteLines : List<String>) : void
+ addPerformBeforeEachLine(parsedTestSuiteLines : List<String>) : void
+ addPerformAfterEachLine(parsedTestSuiteLines : List<String>) : void
addIncrementTestCaseCountLine(parsedTestSuiteLines : List<String>) : void
addTestCodeForAssertion(parsedTestSuiteLines : List<String>, numericFields : NumericFields) : void
addTestCodeFor88LevelEqualityCheck(parsedTestSuiteLines : List<String>) : void
addSetNormalOrReverseCompare(parsedTestSuiteLines : List<String>) : void
addLinesForCurrentVerifyStatement(parsedTestSuiteLines : List<String>) : void
addFinalLines(parsedTestSuiteLines : List<String>) : void
fieldIsANumericDataType(fieldNameForExpect : String) : boolean
appendTokenToCobolStatement(testSuiteToken : String) : void
addUserWrittenCobolStatement(parsedTestSuiteLines : List<String>) : void
- getLinesUntilKeywordHit(testSuiteReader : BufferedReader, endingKeyword : String, currentKey : String, skipCurrentToken : boolean) : List<String>
- initializeCobolStatement() : void
+ getCurrentTestSuiteName() : String
+ getCurrentTestCaseName() : String
+ getCobolStatement() : String
+ getCurrentFieldName() : String
+ getWhenOtherSectionOrParagraph(type : String, lines : List<String>, itdentifier : String, withComments : boolean) : WhenOther
}
class LaunchHelper{
{static} generateCommandParms(processKey : String, programName : String, compileOptions : List<String>, surroundWithQuotes : boolean) : String[]
}
class ComponentMockedTwiceInSameScopeException{
+ ComponentMockedTwiceInSameScopeException(message : String)
}
ComponentMockedTwiceInSameScopeException --|> RuntimeException
class FileNameMatcher{
- matcher : PathMatcher
- matchingFiles : List<String>
- defaultToAllFiles : boolean
+ FileNameMatcher(pattern : String)
+ getMatchingFiles() : List<String>
find(file : Path) : void
+ visitFile(file : Path, attrs : BasicFileAttributes) : FileVisitResult
+ preVisitDirectory(dir : Path, attrs : BasicFileAttributes) : FileVisitResult
+ visitFileFailed(file : Path, exc : IOException) : FileVisitResult
}
FileNameMatcher --|> SimpleFileVisitor
class TestSuiteConcatenator{
- testFileNames : String
+ TestSuiteConcatenator(testFileNames : String)
concatenateTestSuites(programTestSuiteSubdirectory : String) : Reader
}
class ArgumentHandler{
- options : Map<OptionKey,OptionValue>
- {static} LONG_OPT_PREFIX : String
- {static} SHORT_OPT_PREFIX : String
- {static} LONG_OPT_KEYWORD : String
- {static} ARGUMENT_REQUIRED_INDICATOR : char
- {static} canTakeMultipleArguments : List<String>
+ ArgumentHandler(args : String[], optionsString : String)
+ getValueFor(key : String) : String
+ isSet(key : String) : boolean
- storeOptionSettings(optionsString : String) : void
- processCommandLineArgumentArray(args : String[]) : void
+ loadArgProgramPaths() : void
- lookupOption(requestedOption : String) : OptionValue
- isKey(argValue : String) : boolean
- stripPrefix(argValue : String) : String
}
class WhenOther{
- identifier : String
- type : String
- lines : List<String>
- testSuiteNumber : int
- testCaseNumber : int
- mockNumber : int
+ WhenOther(testSuiteNumber : int, testCaseNumber : int, mockNumber : int)
+ getGeneratedWhenOtherIdentifier() : String
+ getGeneratedWhenOtherIdentifierRoot() : String
+ addLines(lines : List<String>) : void
+ setType(type : String) : void
+ getType() : String
+ getLines() : List<String>
+ setIdentifier(identifier : String) : void
+ getCommentText() : List<String>
}
class RunInfo{
- {static} currentProgramName : String
- {static} currentProgramPath : String
- {static} testSuiteNameToPathMap : Map<String,String>
- {static} configFilePath : String
- {static} generatedCobolSourcePath : String
- {static} compiledProgramPath : String
+ {static} setCurrentProgramName(programName : String) : void
+ {static} getCurrentProgramName() : String
+ {static} getCurrentProgramPath() : String
+ {static} setCurrentProgramPath(currentProgramPath : String) : void
+ {static} getTestSuitePath(testSuiteName : String) : String
+ {static} addTestSuiteNameToPathMapKeyValuePair(testSuiteName : String, path : String) : void
+ {static} getConfigFilePath() : String
+ {static} setConfigFilePath(configFilePath : String) : void
+ {static} getGeneratedCobolSourcePath() : String
+ {static} setGeneratedCobolSourcePath(generatedCobolSourcePath : String) : void
+ {static} getCompiledProgramPath() : String
}
class Formatter{
- testSuiteKeyword : String
- passKeyword : String
- failPrefixKeyword : String
- failKeyword : String
- expectedKeyword : String
- verifyCompareKeywords : List<String>
- expectKeyword : String
- verifyKeyword : String
- testCasesExecutedText : String
- tokenExtractor : TokenExtractor
- expectTestSuiteName : boolean
- failData : String
- expectFailMessage : boolean
- expectWasMessage : boolean
- expectExpectedMessage : boolean
# dataTransferObject : DataTransferObject
- expectNumberPassed : boolean
- expectNumberFailed : boolean
+ Formatter(dataTransferObjectStyle : DataTransferObjectStyle)
+ {abstract} writeInFormat(path : String) : String
+ parseText(text : String, testSuitePackage : String) : void
- setTestCaseValues(line : String) : void
- getFailureType(line : String) : String
- instantiateBasedOnStyle(style : DataTransferObjectStyle) : DataTransferObject
}
class CopybookCouldNotBeExpanded{
+ CopybookCouldNotBeExpanded(cause : Throwable)
}
CopybookCouldNotBeExpanded --|> RuntimeException
class Emitter{
- helpText : String[]
emitHelp() : void
emitVersion() : void
emitByLine(text : String[]) : void
}
class CopybookExpander{
- pathToCopybooks : String
- copybookFilenameSuffixes : List<String>
+ CopybookExpander()
+ expand(expandedLines : List<String>, copybookFilename : String) : List<String>
+ expand(expandedLines : List<String>, copybookFilename : String, textReplacement : StringTuple) : List<String>
- commentOut(sourceLine : String) : String
- copyStatementIsPresentIn(sourceLine : String) : boolean
- extractCopybookNameFrom(sourceLine : String) : String
- getPathToCopybooks() : String
+ expandDB2(expandedLines : List<String>, copybookFilename : String, textReplacement : StringTuple) : List<String>
}
class ProcessLauncherException{
+ ProcessLauncherException(message : String)
+ ProcessLauncherException(cause : Throwable)
+ ProcessLauncherException(message : String, cause : Throwable)
}
ProcessLauncherException --|> RuntimeException
class IO_FileGetter{
{static} getSourceReader(programName : String) : Reader
{static} getTestSourceWriter(sourceFile : String) : Writer
{static} getMatchingTestDirectoriesForProgram(programName : String) : List<String>
}
class MockRepository{
- mocks : List<Mock>
+ addMock(mock : Mock) : void
+ getMocks() : List<Mock>
+ mockExistsFor(identifier : String, type : String, arguments : List<String>) : boolean
+ getMockFor(identifier : String, type : String, testSuite : String, testCase : String, arguments : List<String>) : Mock
- mockAlreadyExist(mock : Mock) : boolean
}
class CobolSourceCouldNotBeReadException{
+ CobolSourceCouldNotBeReadException(cause : Throwable)
}
CobolSourceCouldNotBeReadException --|> RuntimeException
class PrepareMergeController{
+ {static} getSourceReader(programName : String) : Reader
+ {static} getTestSourceWriter(sourceFile : String) : Writer
+ {static} getTestSourceOutPath() : String
+ {static} getMatchingTestDirectoriesForProgram(programName : String) : List<String>
}
class EnvironmentSetup{
loadConfigurationSettings(configFileFromCommandLine : String) : void
setLogLevel(logLevelFromCommandLine : String) : void
}
class CobolReader{
- reader : BufferedReader
- state : State
- tokenExtractor : TokenExtractor
- previousLine : CobolLine
- previousMeaningfulLine : CobolLine
- currentLine : CobolLine
- nextLines : List<CobolLine>
- currentStatement : List<CobolLine>
- lineNumber : int
- lineJustEntered : String
- maxLineLength : int
+ CobolReader(sourceReader : BufferedReader)
getState() : State
getCurrentLine() : CobolLine
getPreviousLine() : CobolLine
getPreviousMeaningfulLine() : CobolLine
getCurrentStatement() : List<CobolLine>
+ getLineJustEntered() : String
hasStatementBeenRead() : boolean
getLineNumber() : int
readLine() : CobolLine
readStatementAsOneLine() : CobolLine
- setPreviousMeaningfulLine() : void
updateState() : void
close() : void
appendNextMeaningfulLineToCurrentLine(isFirstTime : Boolean) : CobolLine
appendToCurrentLine(appendString : String) : CobolLine
removePeriodFromCurrentLine() : CobolLine
addLineBeforeCurrentRead(line : String) : void
addLineAfterCurrentRead(line : String) : void
peekNextMeaningfulLine() : CobolLine
putNextLine(line : CobolLine) : void
putNextLine(line : String) : void
readTillEndOfStatement() : List<CobolLine>
readTillHitToken(token : String, ignoreTokenOnCurrentLine : boolean) : List<CobolLine>
isFlagSet(partOfProgram : String) : boolean
}
class EnvironmentSetupController{
environmentSetup : EnvironmentSetup
+ EnvironmentSetupController()
+ runSetup(configFileFromCommandLine : String, logLevelFromCommandLine : String) : void
}
class Keyword{
- value : String
- validNextKeys : List<String>
- validNextKeysInContext : Map<String,List<String>>
- keywordAction : KeywordAction
+ Keyword(value : String, validNextKeys : List<String>, keywordAction : KeywordAction)
+ Keyword(value : String, validNextKeys : List<String>, validNextKeysInContext : Map<String,List<String>>, keywordAction : KeywordAction)
+ value() : String
+ getValidNextKeys(context : String) : List<String>
+ keywordAction() : KeywordAction
}
class PlatformLookup{
+ {static} get() : Platform
+ {static} get(osNameValue : String) : Platform
}
class TestSuiteErrorLog{
- lastKeyword : Keyword
- lastToken : String
- fileMessage : String
- lineIndexMessage : String
- followingExpectedGotMessage : String
- followingExpectedInContextGotMessage : String
- keywordInBlock : String
- errorOccured : boolean
- cobolCheckStartingAndEndingKeywords : List<String>
- errorLogPath : String
- errorLogMessages : String
+ TestSuiteErrorLog()
+ hasErrorOccured() : boolean
+ getErrorMessages() : String
+ getLastKeywordValue() : String
+ checkExpectedTokenSyntax(currentKeyword : Keyword, currentToken : String, currentFile : String, lineNumber : int, lineIndex : int) : boolean
+ checkSyntaxInsideBlock(blockKeyword : String, cobolLines : List<String>, tokenExtractor : TokenExtractor, currentFile : String, lineNumber : int) : void
+ logIdenticalMocks(mock : Mock) : void
+ logVerifyReferencesNonExistentMock(verify : VerifyMockCount) : void
+ logUnusedMocks(mocks : List<Mock>) : void
+ logVariableTypeMismatch(expectedType : String, actualType : String, currentFile : String, lineNumber : int, lineIndex : int) : void
- outputError(error : String) : void
- displayErrorType(errorType : ErrorTypes) : String
- getTestSuiteParserErrorLogPath() : String
- initializeTestSuiteErrorLogWriter(path : String) : void
}
class Interpreter{
- {static} SPACE : String
- {static} batchFileIOVerbs : List<String>
- {static} minimumMeaningfulSourceLineLength : int
- {static} commentIndicatorOffset : int
- {static} commentIndicators : List<Character>
- {static} sequenceNumberAreaEnd : int
- {static} indicatorAreaEnd : int
- {static} A_AreaEnd : int
- {static} B_AreaEnd : int
+ {static} getSequenceNumberAreaIndex() : int
+ {static} setFlagsForCurrentLine(line : CobolLine, nextLine : CobolLine, state : State) : String
+ {static} isEndOfStatement(currentLine : CobolLine, nextMeaningfulLine : CobolLine) : boolean
+ {static} lineEndsParagraphOrSection(currentLine : CobolLine, nextLine : CobolLine, lineFollowingNext : CobolLine, state : State) : boolean
+ {static} isTooShortToBeMeaningful(line : CobolLine) : boolean
+ {static} isComment(line : CobolLine) : boolean
+ {static} isComment(line : String) : boolean
+ {static} isMeaningful(line : CobolLine) : boolean
+ {static} isEmpty(line : CobolLine) : boolean
+ {static} shouldLineBeParsed(line : CobolLine, state : State) : boolean
+ {static} shouldLineBeStubbed(line : CobolLine, state : State) : boolean
+ {static} getStubEndToken(line : CobolLine, state : State) : String
+ {static} shouldLineBeReadAsStatement(line : CobolLine, state : State) : boolean
+ {static} lineContainsBinaryFieldDefinition(line : CobolLine) : boolean
+ {static} containsOnlyPeriod(line : CobolLine) : boolean
+ {static} checkForBatchFileIOStatement(line : CobolLine) : boolean
- {static} isBatchFileIOStatement(tokens : List<String>, ioVerb : String) : boolean
+ {static} getSectionOrParagraphName(line : CobolLine) : String
+ {static} isSectionHeader(line : CobolLine, state : State) : boolean
+ {static} isParagraphHeader(line : CobolLine, nextLine : CobolLine, state : State) : boolean
- {static} isParagraphHeaderFormat(line : CobolLine, nextLine : CobolLine) : boolean
+ {static} getUsingArgs(line : CobolLine) : List<String>
+ {static} getBeginningArea(line : CobolLine, ignoreSequenceArea : boolean) : Area
+ {static} isInNumericFormat(token : String) : boolean
+ {static} endsInPeriod(line : CobolLine) : boolean
+ {static} endsInPeriod(lines : List<CobolLine>) : boolean
+ {static} updateCurrentDataStructure(currentStatement : List<CobolLine>, currentHierarchy : TreeMap<Integer,String>) : TreeMap<Integer,String>
- {static} determineVariableName(statementWords : String[]) : String
- {static} isInteger(testString : String) : boolean
- {static} determineCobolLevelNumber(levelNumberString : String) : Integer
- {static} extractStatementWords(currentStatement : List<CobolLine>) : String[]
- {static} wholeWordSearch(line : String, word : String) : Boolean
}
class TestSuiteSyntaxException{
+ TestSuiteSyntaxException(message : String)
}
TestSuiteSyntaxException --|> RuntimeException
class Error{
- message : String
- type : String
- text : String
+ getMessage() : String
+ setMessage(value : String) : void
+ getType() : String
+ setType(value : String) : void
+ getText() : String
+ setText(value : String) : void
}
class CobolLine{
- originalString : String
- unNumberedString : String
- trimmedString : String
- tokens : List<String>
+ CobolLine(line : String, tokenExtractor : TokenExtractor)
+ getOriginalString() : String
+ getUnNumberedString() : String
+ getTrimmedString() : String
+ getTokens() : List<String>
+ getToken(index : int) : String
+ tokensSize() : int
+ containsToken(tokenValue : String) : boolean
+ containsAllTokens(tokenValues : Collection<String>) : boolean
+ containsAllTokensInConsecutiveOrder(tokenValues : Collection<String>) : boolean
+ getTokenIndexOf(tokenValue : String) : int
+ endsWithToken(tokenValue : String) : boolean
- removeSequenceNumberArea(originalLine : String) : String
+ convertCobolLinesToCobolLine(cobolLines : List<CobolLine>) : CobolLine
}
class VerifyReferencesNonexistentMockException{
+ VerifyReferencesNonexistentMockException(message : String)
}
VerifyReferencesNonexistentMockException --|> TestSuiteSyntaxException
class CobolGenerator{
- {static} SECTION_HEADER_FORMAT : String
- {static} WHEN_OTHER_SECTION_HEADER_FORMAT : String
- {static} PARAGRAPH_HEADER_FORMAT : String
- {static} ENDING_PERIOD : String
{static} generateParagraphLines(identifier : String, commentLines : List<String>, bodyLines : List<String>) : List<String>
{static} generateCommentBlock(body : String) : List<String>
{static} getInjectStartTagComment() : String
{static} getInjectEndTagComment() : String
{static} getContinueStatement() : String
{static} addStartAndEndTags(lines : List<String>) : void
{static} generateWhenOtherLines(identifier : String, type : String, commentLines : List<String>, bodyLines : List<String>) : List<String>
}
class StatusController{
status : CurrentStatus
emitter : Emitter
+ StatusController()
+ setExitStatusNormal() : void
+ setExitStatusHalt() : void
+ isExitStatusNormal() : boolean
+ isExitStatusHalt() : boolean
+ getSourceProgramNames() : String[]
+ setSourceProgramNames(sourceProgramNames : String[]) : void
+ getTestFileNames() : String
+ setTestFileNames(testFileNames : String) : void
+ emitHelp() : void
+ emitVersion() : void
+ exitProgram() : void
}
class Generator{
- interpreter : InterpreterController
- writerController : WriterController
- testSuiteParserController : TestSuiteParserController
- workingStorageHasEnded : boolean
matchingTestDirectories : List<String>
- currentIdentifier : String
- currentMockType : String
+ Generator()
+ Generator(interpreter : InterpreterController, writerController : WriterController, testSuiteParserController : TestSuiteParserController)
+ prepareAndRunMerge(programName : String, testFileNames : String) : void
- mergeTestSuite() : void
- processingBeforeEchoingSourceLineToOutput() : void
- tryInsertEndEvaluateAtMockedCompomentEnd(sourceLine : String) : String
- writeToSource(sourceLine : String) : void
- processingAfterEchoingSourceLineToOutput() : void
- closeReadersAndWriters(programName : String) : void
- writeWhenOtherSectionOrParagraph(sourceLine : String) : void
- echoingSourceLineToOutput(sourceLine : String) : void
}
class Initializer{
- argumentController : ArgumentHandlerController
- environmentController : EnvironmentSetupController
- statusController : StatusController
+ Initializer(args : String[])
+ run() : void
+ getSourceProgramNames() : String[]
+ getTestFileNames() : String
+ isExitStatusHalt() : boolean
+ exitProgram() : void
+ isLastSourceProgram(name : String) : boolean
+ launchTestProgram() : boolean
+ setExitStatusHalt() : void
}
class DirectoryNameMatcher{
- matcher : PathMatcher
- matchingDirectories : List<String>
+ DirectoryNameMatcher(pattern : String)
+ getMatchingDirectories() : List<String>
+ find(path : Path) : void
+ visitFile(file : Path, attrs : BasicFileAttributes) : FileVisitResult
+ preVisitDirectory(dir : Path, attrs : BasicFileAttributes) : FileVisitResult
+ visitFileFailed(file : Path, exc : IOException) : FileVisitResult
}
DirectoryNameMatcher --|> SimpleFileVisitor
class TestInstance{
- testSuites : List<TestSuite>
- testingPrograms : String
- testSuiteNumber : int
- testSuiteNumberFailed : int
- testCaseNumber : int
- testCaseNumberFailed : int
+ getTestSuites() : List<TestSuite>
+ addTestSuite(testSuite : TestSuite) : void
+ getTestingPrograms() : String
+ getTestSuiteNumber() : int
+ getTestSuiteNumberPassed() : int
+ getTestSuiteNumberFailed() : int
+ incrementFailedTestSuites() : void
+ getTestCaseNumber() : int
+ getTestCaseNumberPassed() : int
+ getTestCaseNumberFailed() : int
}
class Log{
- {static} currentLogLevel : LogLevel
+ {static} off() : void
+ {static} set(level : LogLevel) : void
+ {static} level() : LogLevel
+ {static} fatal(message : String) : void
+ {static} error(message : String) : void
+ {static} warn(message : String) : void
+ {static} info(message : String) : void
+ {static} debug(message : String) : void
+ {static} trace(message : String) : void
- {static} write(message : String) : void
}
class Testsuite{
- name : String
- tests : String
- disabled : String
- errors : String
- failures : String
- hostname : String
- testsuiteId : String
- testsuitePackage : String
- skipped : String
- time : String
- timestamp : String
- properties : Properties
- testcase : List<Testcase>
- systemOut : String
- systemErr : String
+ getProperties() : Properties
+ setProperties(value : Properties) : void
+ getTestcase() : List<Testcase>
+ setTestcase(value : List<Testcase>) : void
+ addTestCase(value : Testcase) : void
+ getSystemOut() : String
+ setSystemOut(value : String) : void
+ getSystemErr() : String
+ setSystemErr(value : String) : void
+ getName() : String
+ setName(value : String) : void
+ getTests() : String
+ setTests(value : String) : void
+ getDisabled() : String
+ setDisabled(value : String) : void
+ getErrors() : String
+ setErrors(value : String) : void
+ getFailures() : String
+ setFailures(value : String) : void
+ getHostname() : String
+ setHostname(value : String) : void
+ getID() : String
+ setID(value : String) : void
+ getTestsuitePackage() : String
+ setTestsuitePackage(value : String) : void
+ getSkipped() : String
+ setSkipped(value : String) : void
+ getTime() : String
+ setTime(value : String) : void
+ getTimestamp() : String
+ setTimestamp(value : String) : void
}
class TokenTracker{
summizedTokensForArgument : String
parseDataUsingForSummizedTokens : String
lastAddedTokenToArgumentIsQualifier : boolean
+ reset() : void
+ toString() : String
}
class NumericFields{
- fieldTypes : Map<String,DataType>
+ dataTypeOf(fieldName : String) : DataType
+ setDataTypeOf(fieldName : String, dataType : DataType) : void
+ reset() : void
- argumentCheck(argumentValue : Object, messageId : String) : void
- getKeyBasedOnAssumedDataStructure(line : String) : String
}
class Constants{
+ {static} STATUS_NORMAL : int
+ {static} STATUS_HALT : int
+ {static} COMMENT_SPACE_OFFSET : int
+ {static} COBOLCHECK_PACKAGE_PATH : String
+ {static} COBOLCHECK_COPYBOOK_DIRECTORY : String
+ {static} COMMAND_lINE_OPTIONS : String
+ {static} EMPTY_STRING : String
+ {static} NEWLINE : String
+ {static} FILE_SEPARATOR : String
+ {static} CURRENT_DIRECTORY : String
+ {static} PERIOD : String
+ {static} COMMENT_INDICATOR : String
+ {static} COLON : String
+ {static} SPACE : String
+ {static} COMMA : String
+ {static} QUOTE : String
+ {static} APOSTROPHE : String
+ {static} PSEUDO_TEXT_DELIMITER_EQUALS : String
+ {static} PSEUDO_TEXT_DELIMITER_COLON : String
+ {static} TRUE : String
+ {static} FALSE : String
+ {static} TESTSUITE_KEYWORD : String
+ {static} TESTCASE_KEYWORD : String
+ {static} EXPECT_KEYWORD : String
+ {static} FIELDNAME_KEYWORD : String
+ {static} TO_BE_KEYWORD : String
+ {static} TO_EQUAL_KEYWORD : String
+ {static} NOT_KEYWORD : String
+ {static} ALPHANUMERIC_LITERAL_KEYWORD : String
+ {static} PARENTHESIS_ENCLOSED_KEYWORD : String
+ {static} NUMERIC_LITERAL_KEYWORD : String
+ {static} COBOL_TOKEN : String
+ {static} BOOLEAN_VALUE : String
+ {static} REPLACING_KEYWORD : String
+ {static} BY_KEYWORD : String
+ {static} EQUAL_SIGN_KEYWORD : String
+ {static} NOT_EQUAL_SIGN_KEYWORD : String
+ {static} GREATER_THAN_SIGN_KEYWORD : String
+ {static} LESS_THAN_SIGN_KEYWORD : String
+ {static} GREATER_THAN_EQUAL_TO_SIGN_KEYWORD : String
+ {static} LESS_THAN_EQUAL_TO_SIGN_KEYWORD : String
+ {static} MOCK_KEYWORD : String
+ {static} MOCK_TYPE : String
+ {static} QUALIFIED_FIELD_NAME : String
+ {static} ENDMOCK_KEYWORD : String
+ {static} VERIFY_KEYWORD : String
+ {static} NEVER_HAPPENED_KEYWORD : String
+ {static} HAPPENED_KEYWORD : String
+ {static} ONCE_KEYWORD : String
+ {static} AT_LEAST_KEYWORD : String
+ {static} NO_MORE_THAN_KEYWORD : String
+ {static} TIME_KEYWORD : String
+ {static} TIMES_KEYWORD : String
+ {static} BEFORE_EACH_TOKEN : String
+ {static} END_BEFORE_TOKEN : String
+ {static} AFTER_EACH_TOKEN : String
+ {static} END_AFTER_TOKEN : String
+ {static} NUMERIC_KEYWORD : String
+ {static} IN_KEYWORD : String
+ {static} OF_KEYWORD : String
+ {static} BEFORE_EACH_TOKEN_HYPHEN : String
+ {static} AFTER_EACH_TOKEN_HYPHEN : String
+ {static} PARA_TOKEN : String
+ {static} IGNORED_TOKENS : List<String>
+ {static} CONCATENATED_TEST_SUITES_CONFIG_KEY : String
+ {static} DEFAULT_CONCATENATED_TEST_SUITES_PATH : String
+ {static} TEST_PROGRAM_NAME_CONFIG_KEY : String
+ {static} DEFAULT_TEST_PROGRAM_NAME : String
+ {static} PROCESS_CONFIG_KEY : String
+ {static} COBOLCHECK_PREFIX_CONFIG_KEY : String
+ {static} DEFAULT_COBOLCHECK_PREFIX : String
+ {static} TEST_CODE_PREFIX_PLACEHOLDER : String
+ {static} TESTS_OPTION : String
+ {static} PROGRAMS_OPTION : String
+ {static} IDENTIFICATION_DIVISION : String
+ {static} ENVIRONMENT_DIVISION : String
+ {static} CONFIGURATION_SECTION : String
+ {static} SPECIAL_NAMES_PARAGRAPH : String
+ {static} INPUT_OUTPUT_SECTION : String
+ {static} FILE_CONTROL : String
+ {static} DATA_DIVISION : String
+ {static} PROCEDURE_DIVISION : String
+ {static} FILE_SECTION : String
+ {static} LOCAL_STORAGE_SECTION : String
+ {static} LINKAGE_SECTION : String
+ {static} WORKING_STORAGE_SECTION : String
+ {static} SELECT_TOKEN : String
+ {static} FILE_STATUS_TOKEN : String
+ {static} IS_TOKEN : String
+ {static} DECIMAL_POINT_KEYWORD : String
+ {static} COMMA_KEYWORD : String
+ {static} FD_TOKEN : String
+ {static} LEVEL_01_TOKEN : String
+ {static} COPY_TOKEN : String
+ {static} SECTION_TOKEN : String
+ {static} CALL_TOKEN : String
+ {static} USING_TOKEN : String
+ {static} BY_REFERENCE_TOKEN : String
+ {static} BY_CONTENT_TOKEN : String
+ {static} BY_VALUE_TOKEN : String
+ {static} DECLARATIVES_TOKEN : String
+ {static} EXIT_TOKEN : String
+ {static} END_SECTION_TOKEN : String
+ {static} END_PARAGRAPH_TOKEN : String
+ {static} END_CALL_TOKEN : String
+ {static} ZERO_TOKEN : String
+ {static} REPLACE_TOKEN : String
+ {static} CBL_TOKEN : String
+ {static} EXEC_SQL_TOKEN : String
+ {static} EXEC_CICS_TOKEN : String
+ {static} END_EXEC_TOKEN : String
+ {static} CONTINUE_TOKEN : String
+ {static} INCLUDE : String
+ {static} BINARY : String
+ {static} COMP_2_VALUE : String
+ {static} COMP_3_VALUE : String
+ {static} COMP_4_VALUE : String
+ {static} COMP_5_VALUE : String
+ {static} COMP_VALUE : String
+ {static} PIC_VALUE : String
+ {static} PICTURE_VALUE : String
+ {static} NUMERIC_PICTURE_CLAUSE_PATTERN : String
+ {static} PARAGRAPH_TOKEN : String
- Constants()
}
class StringTuple{
- first : String
+ second : String
+ StringTuple(first : String, second : String)
+ getFirst() : String
+ getSecond() : String
+ isEmpty() : boolean
}
StringTuple ..|> Tuple
class Replace{
- {static} COBOL_COMMENT_INDICATOR : String
- {static} sourceIsCommentPattern : Pattern
- {static} SOURCE_COMMENT_INDICATOR : int
- {static} replaceOn : boolean
- {static} replaceMap : LinkedList<ReplaceSet>
- {static} inspect_performed : boolean
- {static} inspect_performed_warned : boolean
+ {static} replace(source : String, lineNumber : int) : String
+ {static} replace(source : String) : String
+ {static} inspectProgram(cobolProgram : File) : void
- {static} sourceLineIsComment(source : String) : boolean
+ {static} isReplaceOn() : boolean
+ {static} getReplaceSetsSize() : int
- {static} reset() : void
+ {static} replaceInProgram(program : File) : String
+ {static} showReplaceSets() : void
}
class ConcatenatedTestSuiteIOException{
+ ConcatenatedTestSuiteIOException(message : String)
+ ConcatenatedTestSuiteIOException(cause : Throwable)
+ ConcatenatedTestSuiteIOException(message : String, cause : Throwable)
}
ConcatenatedTestSuiteIOException --|> RuntimeException
class FilePermission{
+ {static} setFilePermissionForAllUsers(path : String, permissions : String) : void
+ {static} setFilePermissionForAllUsers(file : File, permissions : String) : void
}
class Testsuites{
- disabled : String
- errors : String
- failures : String
- name : String
- tests : String
- time : String
- testsuite : List<Testsuite>
+ getTestsuites() : List<Testsuite>
+ setTestsuite(value : List<Testsuite>) : void
+ addTestSuite(value : Testsuite) : void
+ getDisabled() : String
+ setDisabled(value : String) : void
+ getErrors() : String
+ setErrors(value : String) : void
+ getFailures() : String
+ setFailures(value : String) : void
+ getName() : String
+ setName(value : String) : void
+ getTests() : String
+ setTests(value : String) : void
+ getTime() : String
+ setTime(value : String) : void
}
class Config{
+ {static} DECIMAL_POINT_IS_COMMA_CONFIG_KEY : String
+ {static} APPEND_RULES_AND_OPTIONS : String
+ {static} INJECT_START_TAG_CONFIG_KEY : String
+ {static} INJECT_END_TAG_CONFIG_KEY : String
+ {static} STUB_COMMENT_TAG : String
+ {static} GENERATED_CODE_PATH : String
+ {static} DISPLAY_TESTS_WITH_UNMOCK_CALLS_CONFIG_KEY : String
+ {static} TESTSUITEPARSER_ERROR_LOG_PATH : String
+ {static} TESTSUITEPARSER_ERROR_LOG_NAME : String
+ {static} IO_ENCODING_LINUX_KEY : String
+ {static} IO_ENCODING_MACOSX_KEY : String
+ {static} IO_ENCODING_WINDOWS_KEY : String
+ {static} IO_ENCODING_ZOS_KEY : String
+ {static} IO_ENCODING_UNIX_KEY : String
+ {static} GENERATED_FILES_PERMISSION_ALL : String
+ {static} LOCALE_LANGUAGE_CONFIG_KEY : String
+ {static} LOCALE_COUNTRY_CONFIG_KEY : String
+ {static} LOCALE_VARIANT_CONFIG_KEY : String
+ {static} DEFAULT_LOCALE_CONFIG_KEY : String
+ {static} RUN_GENERATED_TESTS_CONFIG_KEY : String
+ {static} RUN_GENERATED_TESTS_DEFAULT : String
+ {static} RESOLVED_APPLICATION_SOURCE_FILENAME_SUFFIX : String
+ {static} APPLICATION_SOURCE_FILENAME_SUFFIX : String
+ {static} RESOLVED_APPLICATION_COPYBOOK_FILENAME_SUFFIX : String
+ {static} APPLICATION_COPYBOOK_FILENAME_SUFFIX : String
+ {static} NONE : String
+ {static} DEFAULT_CONFIG_FILE_PATH : String
+ {static} TEST_RESULTS_FILE_CONFIG_KEY : String
+ {static} TEST_RESULTS_FORMAT_CONFIG_KEY : String
+ {static} TEST_RESULTS_FORMAT_STYLE_CONFIG_KEY : String
+ {static} APPLICATION_SOURCE_DIRECTORY_CONFIG_KEY : String
+ {static} DEFAULT_APPLICATION_SOURCE_DIRECTORY : String
+ {static} COPY_SOURCE_DIRECTORY_CONFIG_KEY : String
+ {static} DEFAULT_COPY_SOURCE_DIRECTORY : String
+ {static} TESTSUITE_DIRECTORY_CONFIG_KEY : String
+ {static} DEFAULT_TESTSUITE_DIRECTORY : String
+ {static} COBOLCHECK_SCRIPT_DIRECTORY_CONFIG_KEY : String
+ {static} DEFAULT_COBOLCHECK_SCRIPT_DIRECTORY : String
+ {static} GNUCOBOL_COMPILE_OPTIONS : String
+ {static} RESOLVED_GNUCOBOL_COMPILE_OPTIONS : String
- {static} settings : Properties
{static} runDirectory : String
- {static} testCodePrefix : String
{static} decimalPointIsComma : boolean
- {static} testSuiteParserErrorLogFileName : String
{static} generatedTestFileName : String
{static} concatenatedTestSuitePath : String
- {static} sourceFolderContext : String
- Config()
+ {static} load() : void
+ {static} load(configResourceName : String) : void
+ {static} changeProperty(propertyName : String, newValue : String) : void
+ {static} getString(key : String) : String
+ {static} getString(key : String, defaultValue : String) : String
+ {static} remove(key : String) : void
+ {static} getDefaultLocale() : Locale
+ {static} setRunDirectory(value : String) : void
+ {static} getTestCodePrefix() : String
+ {static} setDecimalPointIsCommaFromFile() : void
+ {static} isDecimalPointComma() : boolean
+ {static} setDecimalPointIsComma(value : boolean) : void
+ {static} getAppendRulesAndOptions() : String
+ {static} getGeneratedTestCodePath() : String
+ {static} getTestsuiteparserErrorLogPath() : String
+ {static} getTestsuiteparserErrorLogName() : String
+ {static} setTestSuiteParserErrorLogFileName(fileName : String) : void
+ {static} getGeneratedFilesPermissionAll() : String
+ {static} getInjectStartTag() : String
+ {static} getInjectEndTag() : String
+ {static} getStubTag() : String
+ {static} getTestResultFilePathString() : String
+ {static} getGeneratedTestFileName() : String
+ {static} setGeneratedTestFileName(keyValue : String) : void
+ {static} getConcatenatedTestSuitesPath() : String
+ {static} setConcatenatedTestSuitesPath(keyValue : String) : void
+ {static} getTestResultFormat() : TestOutputFormat
+ {static} getCharsetForPlatform(platform : Platform) : String
+ {static} getTestResultFormatStyle() : DataTransferObjectStyle
+ {static} getRunGeneratedTest() : boolean
+ {static} setSourceFolderContext(keyValue : String) : void
+ {static} getApplicationSourceDirectoryPathString() : String
+ {static} getCopyBookSourceDirectoryPathString() : String
+ {static} getTestSourceDirectoryPathString() : String
+ {static} getApplicationFilenameSuffixes() : List<String>
- {static} setApplicationFilenameSuffixes() : void
+ {static} getCopybookFilenameSuffixes() : List<String>
+ {static} getScriptDirectory() : String
+ {static} getGnuCOBOLCompileOptions() : List<String>
+ {static} getDisplayUnMockedCalls() : Boolean
+ {static} setGnuCOBOLCompileOptions() : void
- {static} setCopybookFilenameSuffix() : void
- {static} resolveFilenameSuffixes(configKey : String, resolvedConfigKey : String) : void
- {static} resolveConfigList(configKey : String, resolvedConfigKey : String) : void
- {static} setDefaultLocaleOverride() : void
- {static} getCorrectRunContext(path : String) : String
}
class TestCaseAlreadyExistsException{
+ TestCaseAlreadyExistsException(message : String)
+ TestCaseAlreadyExistsException(cause : Throwable)
+ TestCaseAlreadyExistsException(message : String, cause : Throwable)
}
TestCaseAlreadyExistsException --|> RuntimeException
class WindowsProcessLauncher{
- processConfigKeyPrefix : String
+ WindowsProcessLauncher(processConfigKeyPrefix : String)
+ getProcessConfigKeyPrefix() : String
+ run(programName : String) : Process
}
WindowsProcessLauncher ..|> ProcessLauncher
class OptionKey{
+ shortKey : String
+ longKey : String
}
class TableEmbedDto{
result : String
- htmlCharacterEntityMap : Map<String,String>
+ getDataTransferObject() : Object
- getHeader() : String
- getTime() : String
- getTestOverView() : String
- generateHtmlForTestSuite(testSuite : TestSuite) : String
- formatGeneratedArtifacts(testSuite : TestSuite) : String
- generateHtmlForTestCase(testCase : TestCase) : String
- initializeHtmlCharacterEntitiesMap() : void
- setHtmlCharacterEnities(input : String) : String
}
TableEmbedDto --|> DataTransferObject
class MockGenerator{
- testSuiteIdentifier : String
- testCaseIdentifier : String
- performFormat : String
- endEvaluateLine : String
- continueLine : String
+ {static} performUnMockPara : String
- countMockInitialWSHeader : String
- initializeMockCountParagraphHeader : String
generateWorkingStorageMockCountLines(mocks : List<Mock>) : List<String>
generateMockCountInitializer(mocks : List<Mock>) : List<String>
generateMockParagraphs(mocks : List<Mock>, withComments : boolean) : List<String>
generateMockPerformCalls(identifier : String, type : String, arguments : List<String>, mocks : List<Mock>) : List<String>
getEndEvaluateLine() : String
getContinueLine() : String
- generateMockCountValues(mocks : List<Mock>) : List<String>
- generateParagraphsForMock(mock : Mock, withComment : boolean) : List<String>
}
class Messages{
- {static} messageBundle : ResourceBundle
+ {static} get(messageId : String, substitutionValues : String) : String
+ {static} setLocale(locale : Locale) : void
+ {static} loadResourceBundle() : void
}
class InterpreterController{
- reader : CobolReader
- lineRepository : LineRepository
- numericFields : NumericFields
- tokenExtractor : TokenExtractor
- hasReadLine : boolean
- possibleMockIdentifier : String
- possibleMockType : String
- possibleMockArgs : List<String>
- extractedCopyBook : List<String>
- insideSectionOrParagraphMockBody : boolean
- currentDataStructure : TreeMap<Integer,String>
- stubTag : String
- sectionOrParagraph : SectionOrParagraph
+ InterpreterController(sourceReader : BufferedReader)
+ getFileSectionStatements() : List<String>
+ getFileControlStatements() : List<String>
+ getFileIdentifiersAndStatuses() : Map<String,String>
+ getCopyTokens() : List<String>
+ getNumericFieldDataTypeFor(fieldName : String) : DataType
+ getNumericFields() : NumericFields
+ getTokensForCurrentLine() : List<String>
+ getCurrentStatement() : List<String>
+ getCurrentLineAsStatement() : CobolLine
+ hasStatementBeenRead() : boolean
+ isReading(partOfProgram : String) : boolean
+ didLineJustEnter(partOfProgram : String) : boolean
+ hasReaderStateChanged() : boolean
+ currentLineContains(str : String) : boolean
+ isCurrentComponentMockable() : boolean
+ getPossibleMockIdentifier() : String
+ getPossibleMockType() : String
+ getPossibleMockArgs() : List<String>
+ isInsideSectionOrParagraphMockBody() : boolean
+ setInsideSectionOrParagraphMockBody(insideSectionOrParagraphMockBody : boolean) : void
+ shouldCurrentLineBeParsed() : boolean
+ shouldCurrentLineBeStubbed() : boolean
+ shouldCurrentStatementBeStubbed() : boolean
+ isCurrentLineEndingSectionOrParagraph() : boolean
+ isCurrentLineEndingWorkingStorageSection() : boolean
+ canWriteEndEvaluateBeforeCurrentLine() : boolean
+ interpretNextLine() : String
+ closeReader() : void
- updateDependencies(line : CobolLine) : void
- updateDecimalPointIsComma(line : CobolLine) : void
- updateReplaceStatement(line : CobolLine) : void
- updatePossibleMock(line : CobolLine) : void
- updatePossibleStub(line : CobolLine) : void
- tryReadBatchFileIOStatement() : void
- updateNumericFields(line : CobolLine) : void
- generateVariableNameBasedOnDataStructure(dataStructure : TreeMap<Integer,String>) : String
- updateLineRepository(line : CobolLine) : void
- updateLineRepoBySelectToken(line : CobolLine) : void
- updateLineRepoByFileStatusToken(line : CobolLine) : void
- updateLineRepoByCopyStatement() : void
- updateCBLOptions(line : CobolLine) : void
- peekNextMeaningfulLineAndGetTokenAtIndex0() : String
- convertToStrings(lines : List<CobolLine>) : List<String>
- resetPossibleMockValues() : void
+ getSectionOrParagraphLines() : List<String>
+ removeSectionOrParagraphLines() : void
+ addSectionOrParagraphLine() : void
+ addSectionOrParagraphLine(line : String) : void
+ addSectionOrParagraphLines(lines : List<String>) : void
}
class XMLFormat{
+ XMLFormat(dataTransferObjectStyle : DataTransferObjectStyle)
+ writeInFormat(path : String) : String
}
XMLFormat --|> Formatter
class BeforeAfterItem{
name : String
testSuite : String
lines : List<String>
BeforeAfterItem(name : String, testSuite : String, lines : List<String>)
}
class Skipped{
- message : String
+ getMessage() : String
+ setMessage(value : String) : void
}
class Launcher{
launchProgram(launcher : ProcessLauncher, programPath : String, postLaunchAction : Consumer<Process>) : int
launchProgram(launcher : ProcessLauncher, programPath : String) : int
+ getPlatformSpecificLauncher(platform : Platform) : ProcessLauncher
}
class PathHelper{
- PathHelper()
+ {static} getTestSourceOutPath() : String
+ {static} appendMatchingFileSuffix(filePath : String, applicationSuffixes : List<String>) : String
+ {static} getMatchingDirectories(name : String, path : String) : List<String>
+ {static} endWithFileSeparator(path : String) : String
+ {static} findFilePath(path : String, fileName : String, possibleExtensions : List<String>) : String
}
class IOExceptionProcessingConfigFile{
+ IOExceptionProcessingConfigFile(filename : String)
+ IOExceptionProcessingConfigFile(ex : Throwable)
+ IOExceptionProcessingConfigFile(filename : String, ex : Throwable)
}
IOExceptionProcessingConfigFile --|> RuntimeException
class ReplaceSet{
- from : String
- to : String
- trailing : boolean
- leading : boolean
- fromSourceLine : int
- untilSourceLine : int
+ ReplaceSet(from : String, to : String, trailing : boolean, leading : boolean, fromSourceLine : int, untilSourceLine : int)
+ ReplaceSet()
+ replaceInline(line : String) : String
+ replaceInline(line : String, sourceLine : int) : String
+ setTrailing(trailing : boolean) : void
+ setLeading(leading : boolean) : void
+ setFrom(value : String) : void
+ setTo(value : String) : void
+ getFrom() : String
+ getTo() : String
+ isTrailing() : boolean
+ isLeading() : boolean
+ setFromSourceLine(sourceLineNumber : int) : void
+ setUntilSourceLine(sourceLineNumber : int) : void
+ getFromSourceLine() : int
+ getUntilSourceLine() : int
+ toString() : String
}
class State{
- flags : Map<String,Flag>
+ State()
+ getFlags() : Map<String,Flag>
+ setFlagFor(key : String) : void
+ unsetFlagFor(key : String) : void
+ isFlagSetFor(key : String) : boolean
- mutuallyExclusiveFlagsFor(token : String, mutuallyExclusiveTokens : String) : void
- dependentFlagsFor(token : String, dependentTokens : String) : void
}
class LineRepository{
- currentExpectFileIdentifier : String
- fileControlStatements : List<String>
- fileSectionStatements : List<String>
- fileIdentifiersAndStatuses : Map<String,String>
- copyTokens : List<String>
LineRepository()
getFileControlStatements() : List<String>
getFileSectionStatements() : List<String>
getFileIdentifiersAndStatuses() : Map<String,String>
getCopyTokens() : List<String>
setCopyTokens(copyTokens : List<String>) : void
addFileControlStatement(statement : String) : void
addFileSectionStatement(statement : String) : void
putFileIdentifierAndStatus(key : String, value : String) : void
addFileIdentifierWithNoStatus(identifier : String) : void
addStatusForLastSetIdentifier(status : String) : void
addCopyToken(token : String) : void
addAccumulatedTokensFromCopyStatementToCopyTokens(line : String) : void
addExpandedCopyStatementsToFileSectionStatements() : List<String>
addExpandedCopyDB2Statements(line : CobolLine) : List<String>
}
class TestCase{
name : String
passed : boolean
failMessage : String
+ getName() : String
+ setName(name : String) : void
+ didPass() : boolean
+ setPassed(passed : boolean) : void
+ getFailMessage() : String
+ setFailMessage(failMessage : String) : void
}
class TestSuite{
- name : String
- failedTests : int
- testCases : List<TestCase>
- programName : String
- programPath : String
- path : String
+ getName() : String
+ setName(name : String) : void
+ getTests() : int
+ getPassedTests() : int
+ getFailedTests() : int
+ incrementFailedTests() : void
+ getTestCases() : List<TestCase>
+ addTestCase(testCase : TestCase) : void
+ getProgramName() : String
+ setProgramName(programName : String) : void
+ getProgramPath() : String
+ setProgramPath(programPath : String) : void
+ getPath() : String
+ setPath(path : String) : void
}
class ContextHandler{
- {static} currentContext : String
- {static} keyword : Keyword
- {static} startAndEndOfContexts : Map<String,List<String>>
+ {static} tryEnterContext(keyword : String) : void
+ {static} tryExitingContext(keyword : String) : void
+ {static} forceContextExit() : void
+ {static} insideOfContext() : boolean
+ {static} getCurrentContext() : String
+ {static} doesKeyEndContext(key : String) : boolean
}
class LinuxProcessLauncher{
- processConfigKeyPrefix : String
+ LinuxProcessLauncher(processConfigKeyPrefix : String)
+ getProcessConfigKeyPrefix() : String
+ run(programName : String) : Process
}
LinuxProcessLauncher ..|> ProcessLauncher
class Keywords{
- {static} keywordInfo : Map<String,Keyword>
- {static} mockTypes : List<String>
- {static} qualifiedNameKeywords : List<String>
+ {static} getKeywordFor(key : String, expectFieldName : boolean) : Keyword
}
class ArgumentHandlerController{
argumentHandler : ArgumentHandler
+ ArgumentHandlerController(args : String[])
+ ArgumentHandlerController(args : String[], optionsString : String)
+ loadSettingsFromArguments() : void
+ isKeySet(key : String) : boolean
+ getKeyValue(key : String) : String
}
class Property{
- name : String
- value : String
+ getName() : String
+ setName(value : String) : void
+ getValue() : String
+ setValue(value : String) : void
}
class DataTransferObject{
testSuiteIndex : int
testCaseIndex : int
testInstance : TestInstance
lastProgram : String
+ moveToNextTestSuite() : void
+ moveToNextTestCase() : void
+ getDataTransferObject() : Object
+ setNumberOfAllTests(numberofTests : String) : void
+ setNumberOffAllFailures(numberOfFailures : String) : void
+ setCurrentTestSuiteName(name : String) : void
+ setCurrentTestSuiteTests(numberofTests : String) : void
+ setCurrentTestSuiteFailures(numberOfFailures : String) : void
+ setCurrentTestSuitePackage(testSuitePackage : String) : void
+ setCurrentTestCaseName(name : String) : void
+ setCurrentTestCaseFailure(message : String, type : String) : void
+ setCounts() : void
+ setCurrentTestCaseErrorMessage(message : String, type : String) : void
}
class Properties{
- property : List<Property>
+ getProperty() : List<Property>
+ setProperty(value : List<Property>) : void
}
class BeforeAfterRepo{
beforeEachItems : List<BeforeAfterItem>
beforeEachEvaluationGenerator : EvaluationGenerator
afterEachItems : List<BeforeAfterItem>
afterEachEvaluationGenerator : EvaluationGenerator
testCodePrefix : String
- {static} BEFORE_EACH_BRANCH_NAME : String
- {static} AFTER_EACH_BRANCH_NAME : String
- {static} TESTSUITE_NAME_VARIABLE : String
- {static} PERFORM_LINE : String
- {static} BEFORE_EACH_PARAGRAPH_NAME : String
- {static} AFTER_EACH_PARAGRAPH_NAME : String
+ BeforeAfterRepo()
addBeforeEachItem(id : int, testSuiteName : String, lines : List<String>) : void
addAfterEachItem(id : int, testSuiteName : String, lines : List<String>) : void
getBeforeEachParagraphLines() : List<String>
getAfterEachParagraphLines() : List<String>
getAllBranchingParagraphs(withComments : boolean) : List<String>
}
TestSuiteParserController--"- testSuiteParser" TestSuiteParser
TestSuiteParserController--"testSuiteConcatenator" TestSuiteConcatenator
TestSuiteParserController--"- mockRepository" MockRepository
TestSuiteParserController--"- beforeAfterRepo" BeforeAfterRepo
TestSuiteParserController--"- mockGenerator" MockGenerator
TestSuiteParserController--"- whenOtherGenerator" WhenOtherGenerator
TestSuiteParserController--"- testSuiteErrorLog" TestSuiteErrorLog
Testcase--"- skipped" Skipped
Testcase--"- error" Error
Testcase--"- failure" Error
JUnitDto--"- testsuites" Testsuites
ReplaceStatementLocator--"- tokenizer" ReplaceTokenizer
Mock--"- scope" MockScope
WriterController--"- cobolWriter" CobolWriter
ProcessOutputWriter--"xmlFormat" XMLFormat
ProcessOutputWriter--"htmlFormat" HTMLFormat
LauncherController--"- launcher" Launcher
LauncherController--"- processOutputWriter" ProcessOutputWriter
VerifyMockCount--"- attachedMock" Mock
ReplaceToken--"- type" ReplaceTokenType
CobolTestRunner--"controller" LauncherController
TestSuiteParser--"- keywordExtractor" KeywordExtractor
TestSuiteParser--"- testSuiteWritingStyle" TestSuiteWritingStyle
TestSuiteParser--"- testSuiteErrorLog" TestSuiteErrorLog
TestSuiteParser--"- beforeAfterRepo" BeforeAfterRepo
TestSuiteParser--"mockRepository" MockRepository
TestSuiteParser--"- currentMock" Mock
TestSuiteParser--"- currentVerify" VerifyMockCount
TestSuiteParser--"- nextAction" KeywordAction
TestSuiteParser--"- numericFields" NumericFields
Formatter--"- tokenExtractor" TokenExtractor
Formatter--"# dataTransferObject" DataTransferObject
CobolReader--"- state" State
CobolReader--"- tokenExtractor" TokenExtractor
CobolReader--"- previousLine" CobolLine
CobolReader--"- previousMeaningfulLine" CobolLine
CobolReader--"- currentLine" CobolLine
EnvironmentSetupController--"environmentSetup" EnvironmentSetup
Keyword--"- keywordAction" KeywordAction
TestSuiteErrorLog--"- lastKeyword" Keyword
StatusController--"status" CurrentStatus
StatusController--"emitter" Emitter
Generator--"- interpreter" InterpreterController
Generator--"- writerController" WriterController
Generator--"- testSuiteParserController" TestSuiteParserController
Initializer--"- argumentController" ArgumentHandlerController
Initializer--"- environmentController" EnvironmentSetupController
Initializer--"- statusController" StatusController
Log--"- {static} currentLogLevel" LogLevel
Testsuite--"- properties" Properties
Config--"- {static} settings" Properties
InterpreterController--"- reader" CobolReader
InterpreterController--"- lineRepository" LineRepository
InterpreterController--"- numericFields" NumericFields
InterpreterController--"- tokenExtractor" TokenExtractor
InterpreterController--"- sectionOrParagraph" SectionOrParagraph
ContextHandler--"- {static} keyword" Keyword
ArgumentHandlerController--"argumentHandler" ArgumentHandler
DataTransferObject--"testInstance" TestInstance
BeforeAfterRepo--"beforeEachEvaluationGenerator" EvaluationGenerator
BeforeAfterRepo--"afterEachEvaluationGenerator" EvaluationGenerator
interface Tuple{
getFirst() : T1
getSecond() : T2
isEmpty() : boolean
}
interface ProcessLauncher{
getProcessConfigKeyPrefix() : String
run(programName : String) : Process
}
interface TokenExtractor{
extractTokensFrom(sourceLine : String) : List<String>
}
enum TestSuiteWritingStyle{
Freeform
Strict
}
enum Area{
NONE
SEQUENCE_NUMBER
INDICATOR
A
B
}
enum DataTransferObjectStyle{
directOutput
tableDocument
tableEmbed
JUnit
}
enum ReplaceTokenType{
REPLACE
LEADING
TRAILING
BY
TERMINATOR
OTHER
}
enum Platform{
LINUX
UNIX
WINDOWS
OSX
ZOS
}
enum KeywordAction{
NONE
ACTUAL_FIELDNAME
BOOLEAN_COMPARE
COBOL_STATEMENT
EXPECTED_VALUE
FIELDNAME
IGNORE
NEW_TESTCASE
REVERSE_LOGIC
TESTSUITE_NAME
}
enum MockScope{
Local
Global
}
enum DataType{
ALPHANUMERIC
BINARY
PACKED_DECIMAL
FLOATING_POINT
DISPLAY_NUMERIC
}
enum TestOutputFormat{
txt
xml
html
}
enum LogLevel{
OFF
FATAL
ERROR
WARN
INFO
DEBUG
TRACE
}
enum ErrorTypes{
SYNTAX_ERROR
RUNTIME_ERROR
WARNING
}
@enduml