#!/bin/sh
# Linux - compile and execute a test Cobol program
#
# Assumptions:
#
# GnuCOBOL 3.+ is installed and on the path. Its executable or alias or symlink is named "cobc".

cobc -x $@
name=$(echo "$1" | cut -f 1 -d '.')
"./${name}"

